checkpoint_dir: checkpoints/bert_lora_triplet
dataset:
  name: sentence-transformers/all-nli
  split: train[:1%]
  subset: triplet
dist_parameters:
  cast_forward_inputs: false
  dcp_api: true
  distribute_api: dcp_api
  dtensor_api: false
  mixed_precision: false
  output_dtype: bfloat16
  param_dtype: bfloat16
  reduce_dtype: float32
model_name: bert-base-uncased
model_type: llm
multi_dimensional_parallelism:
  device_mesh_shape:
  - 2
  - 2
  dp_enabled: false
  dp_size: 0
  enabled: false
  n_microbatches: 4
  pp_enabled: false
  pp_schedule: 1f1b
  pp_size: 0
  tp_enabled: false
  tp_size: 0
num_gpus: 1
peft:
  alpha: 32
  bias: none
  dropout: 0.05
  enabled: true
  r: 16
  target_modules: all-linear
  type: lora
prefetch:
  backward: 2
  explicit: true
  forward: 2
quantization:
  bits: 4
  compute_dtype: bfloat16
  double_quant: true
  enabled: false
  quant_type: nf4
save: true
save_load:
  load_model_from_hf: true
  resume: false
  resume_path: ''
strategy: solo
training:
  batch_size: 32
  epochs: 5
  grad_clip: 1
  gradient_checkpointing: true
  learning_rate: 0.0001
  max_length: 256
  warmup_steps: 100
  weight_decay: 0.01
wandb:
  wandb_entity: dist-train-project
  wandb_log_with_train: false
  wandb_project: dist-train-project
